server:
  port: 8072
  
logstash.host: ${LOGSTASH_SERVER_URL:3.136.161.26:5000}
 
logging: 
  config: classpath:logback-delayed.xml
  
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${REG_SERVER_URL:http://localhost:8070/eureka/}
      
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: book-backend
          uri: lb://book-backend
          predicates:
          - Path=/book-proxy/**
          filters:
          - RewritePath=/book-proxy/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
   
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
        