FROM node:18.16.1 as build

LABEL maintainer="Justin Zhou <zhum11@126.com>"

WORKDIR /app
COPY ./public /app
COPY ./src /app
COPY ./package.json /app/package.json
COPY ./yarn.lock /app/yarn.lock


RUN yarn config set registry "https://registry.npmmirror.com"
RUN yarn global add create-react-app
RUN yarn run build


FROM nginx:latest

WORKDIR application

#copy the static compiled react app js, html  from  previous build to nginx static file folder.
COPY --from=build /app/build/ /usr/share/nginx/html