---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: justin-book-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: justin-book-frontend
  template:
    metadata:
      labels:
        app: justin-book-frontend
    spec:
      containers:
        - name: justin-book-frontend
          image: book/book-frontend:0.0.1-SNAPSHOT
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: justin-book-frontend
  labels:
    app: justin-book-frontend
spec:
  selector:
    app: justin-book-frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31400
      protocol: TCP
